# Taskfile.yml
version: '3'

vars:
  APP_NAME: app-cs.exe
  BUILD_DIR: "build"


tasks:
  build:
    desc: Build app in release mode
    cmds:
      - dotnet build -o build
      - dotnet clean

  run:
    desc: Run built binary
    deps: [build]
    cmds:
      - ./{{.BUILD_DIR}}/{{.APP_NAME}}
