[package]
name = "app-rust"
version = "0.1.0"
edition = "2024"
publish = false

[build]
    target-dir = "build"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true

[dependencies]
